name: SonarCloud Analysis for Oracle Graal

on:
  pull_request:
    branches:
      - main  
  push:
    branches:
      - main  

jobs:
  sonarcloud:
    name: Analyze with SonarCloud
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Cache SonarCloud dependencies
        uses: actions/cache@v2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonarcloud-${{ hashFiles('**/*.java') }}
          restore-keys: |
            ${{ runner.os }}-sonarcloud-

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v1.5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectKey: ${{ secrets.SONAR_PROJECT_KEY }}  # Set the project key for this repo in SonarCloud
          organization: "your-organization"  # Adjust this with your SonarCloud organization

      - name: Quality Gate Check
        run: |
          echo "Waiting for Quality Gate..."
          curl -u $SONAR_TOKEN: https://sonarcloud.io/api/qualitygates/project_status?projectKey=${{ secrets.SONAR_PROJECT_KEY }} | jq -r .projectStatus.status
