name: Analyze First Commit of Selected PRs

on:
  workflow_dispatch:  # Allows manual execution
  push:
    branches:
      - "pr-*-before-improvements"  # Runs when first commit branches are pushed

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure we get full commit history

      - name: Set up CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: java

      - name: Build Database for CodeQL Analysis
        run: codeql database create db --language=java --source-root=.

      - name: Run CodeQL Analysis
        run: codeql analyze db --format=sarif -o results.sarif

      - name: Upload Analysis Results
        uses: actions/upload-artifact@v3
        with:
          name: codeql-results
          path: results.sarif
