name: "CodeQL Analysis for Specific PRs"
on:
  pull_request:
    branches:
      - main  # Adjust this to the target branch of your PRs
    paths:
      - "pr-*-before-improvements/**"  # This ensures it only runs for your specific PR branches (if desired)

jobs:
  analyze:
    name: Analyze code with CodeQL
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: java  # Adjust this depending on the language you are analyzing

      - name: Build code
        run: |
          # Example build commands for Java
          mvn clean compile

      - name: Run CodeQL Analysis
        uses: github/codeql-action/analyze@v1
